#### Task 01  ·  Clean a Messy CSV

In [19]:
import pandas as pd
df = pd.read_csv("messy_students_data.csv")

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     1000 non-null   str
 1   Gender   1000 non-null   str
 2   Grade    1000 non-null   str
 3   Math     1000 non-null   str
 4   Science  1000 non-null   str
 5   English  1000 non-null   str
 6   Total    1000 non-null   int64
dtypes: int64(1), str(6)
memory usage: 54.8 KB

In [3]:
df.shape

(1000, 7)

In [4]:
df.isnull().sum()

Name       0
Gender     0
Grade      0
Math       0
Science    0
English    0
Total      0
dtype: int64

In [5]:
df.head()

      Name Gender     Grade      Math   Science English  Total
0  'Navya'   male        11      47.0      63.0    74.0    184
1    ROHAN      F   Grade 3      16.0        77       8    101
2  'Aditi'      0  Grade 11  28 marks  43 marks    46.0    117
3     Myra   Male         7        74      12.0      72    158
4   ISHAAN   male        03  92 marks        27    25.0    144

In [20]:
df['Name'] = df['Name'].str.title().str.strip().str.strip(" '\" ")
df['Name']

0        Navya
1        Rohan
2        Aditi
3         Myra
4       Ishaan
        ...
995     Saanvi
996     Ishaan
997     Ananya
998    Shaurya
999     Ishaan
Name: Name, Length: 1000, dtype: str

In [21]:
df['Gender'] = ( df['Gender'].astype(str).str.strip().str.title()
    .replace({
        'M': 'Male',
        'F': 'Female',
        '0': None
    })
)

In [8]:
df["Gender"]

0        Male
1      Female
2        None
3        Male
4        Male
        ...
995    Female
996      Male
997    Female
998    Female
999    Female
Name: Gender, Length: 1000, dtype: object

In [22]:
df["Grade"] = (
    df["Grade"]
    .astype(str)
    .str.replace("Grade", "", regex=False)
    .str.strip()
    .str.lstrip("0")
)

In [23]:
df["Grade"] = df["Grade"].astype(int)
df['Grade']

0      11
1       3
2      11
3       7
4       3
       ..
995     9
996    11
997     4
998     7
999     5
Name: Grade, Length: 1000, dtype: int64

In [24]:
df['Math'] = df['Math'].astype(str).str.replace("marks", "", regex=False).str.strip()
df['Math'] = df['Math'].astype(float)
df['Math']

0      47.0
1      16.0
2      28.0
3      74.0
4      92.0
       ...
995    22.0
996    85.0
997    23.0
998    56.0
999    50.0
Name: Math, Length: 1000, dtype: float64

In [25]:
df['Science'] = df['Science'].astype(str).str.replace("marks", "", regex=False).str.strip()
df['Science'] = df['Science'].astype(float)
df['Science']

0      63.0
1      77.0
2      43.0
3      12.0
4      27.0
       ...
995    76.0
996    13.0
997    48.0
998     4.0
999    96.0
Name: Science, Length: 1000, dtype: float64

In [26]:
df['English'] = df['English'].astype(str).str.replace("marks", "", regex=False).str.strip()
df['English'] = df['English'].astype(float)
df['English']

0      74.0
1       8.0
2      46.0
3      72.0
4      25.0
       ...
995     0.0
996    78.0
997    78.0
998    84.0
999    81.0
Name: English, Length: 1000, dtype: float64

In [14]:
df.info

<bound method DataFrame.info of         Name  Gender  Grade  Math  Science  English  Total
0      Navya    Male     11  47.0     63.0     74.0    184
1      Rohan  Female      3  16.0     77.0      8.0    101
2      Aditi    None     11  28.0     43.0     46.0    117
3       Myra    Male      7  74.0     12.0     72.0    158
4     Ishaan    Male      3  92.0     27.0     25.0    144
..       ...     ...    ...   ...      ...      ...    ...
995   Saanvi  Female      9  22.0     76.0      0.0     98
996   Ishaan    Male     11  85.0     13.0     78.0    176
997   Ananya  Female      4  23.0     48.0     78.0    149
998  Shaurya  Female      7  56.0      4.0     84.0    144
999   Ishaan  Female      5  50.0     96.0     81.0    227

[1000 rows x 7 columns]>

In [15]:
df.isnull()

      Name  Gender  Grade   Math  Science  English  Total
0    False   False  False  False    False    False  False
1    False   False  False  False    False    False  False
2    False    True  False  False    False    False  False
3    False   False  False  False    False    False  False
4    False   False  False  False    False    False  False
..     ...     ...    ...    ...      ...      ...    ...
995  False   False  False  False    False    False  False
996  False   False  False  False    False    False  False
997  False   False  False  False    False    False  False
998  False   False  False  False    False    False  False
999  False   False  False  False    False    False  False

[1000 rows x 7 columns]

In [27]:
df = df.dropna()

In [17]:
df.isnull()

      Name  Gender  Grade   Math  Science  English  Total
0    False   False  False  False    False    False  False
1    False   False  False  False    False    False  False
3    False   False  False  False    False    False  False
4    False   False  False  False    False    False  False
5    False   False  False  False    False    False  False
..     ...     ...    ...    ...      ...      ...    ...
995  False   False  False  False    False    False  False
996  False   False  False  False    False    False  False
997  False   False  False  False    False    False  False
998  False   False  False  False    False    False  False
999  False   False  False  False    False    False  False

[927 rows x 7 columns]

In [28]:
# Calculate average score and assign grades
df['score'] = (df['Math'] + df['Science'] + df['English']) / 3

def assign_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 75:
        return 'B'
    elif score >= 50:
        return 'C'
    else:
        return 'F'

df['grade'] = df['score'].apply(assign_grade)
df[['Name', 'Math', 'Science', 'English', 'score', 'grade']]

        Name  Math  Science  English      score grade
0      Navya  47.0     63.0     74.0  61.333333     C
1      Rohan  16.0     77.0      8.0  33.666667     F
3       Myra  74.0     12.0     72.0  52.666667     C
4     Ishaan  92.0     27.0     25.0  48.000000     F
5      Aarav  22.0     87.0     56.0  55.000000     C
..       ...   ...      ...      ...        ...   ...
995   Saanvi  22.0     76.0      0.0  32.666667     F
996   Ishaan  85.0     13.0     78.0  58.666667     C
997   Ananya  23.0     48.0     78.0  49.666667     F
998  Shaurya  56.0      4.0     84.0  48.000000     F
999   Ishaan  50.0     96.0     81.0  75.666667     B

[927 rows x 6 columns]

### export to csv file

In [30]:
df.to_csv('clean_students_data.csv', index=False)